# config/_default/params.toml

colorScheme = "ocean"

defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
mainSections = ["posts"]
enableImageLazyLoading = true
enableQuicklink = true

[homepage]
  layout = "profile" # valid options: page, profile, custom
  showRecent = true
  recentLimit = 10

[header]
  logo = "router.png"
  logoDark = "router.png"
  layout = "hybrid"
  showTitle = true

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = true
  showComments = true
  sharingLinks = ["bluesky", "mastodon", "linkedin", "reddit", "twitter", "pinterest",  "email", "facebook"]

[list]
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = true
  groupByYear = true

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[taxonomy]
  showTermCount = true
